_unit = _this select 0;
_tipo = typeOf _unit;
_loadout = "rhsgref_nat_rifleman";
switch _tipo do
	{
	case "rhsgref_nat_commander": {_loadout = "rhsgref_nat_commander"};
	case "rhsgref_nat_machinegunner_mg42": {_loadout = "rhsgref_nat_machinegunner_mg42"};
	case "rhsgref_nat_grenadier_rpg": {_loadout = "rhsgref_nat_grenadier_rpg"};
	case "rhsgref_nat_medic": {_loadout = "rhsgref_nat_medic"};
	case "rhsgref_nat_saboteur": {_loadout = "rhsgref_nat_saboteur"};
	case "rhsgref_nat_grenadier": {_loadout = "rhsgref_nat_grenadier"};
	case "B_recon_TL_F": {_loadout = NATOSpecOp select 0};
	case "B_CTRG_Soldier_TL_tna_F": {_loadout = NATOSpecOp select 0};
	case "I_Soldier_SL_F": {_loadout = NATOSpecOp select 0};
	case "O_T_Recon_TL_F": {_loadout = CSATSpecOp select 0};
	case "B_recon_M_F": {_loadOut = NATOMarksman};
	case "B_CTRG_Soldier_M_tna_F": {_loadOut = NATOMarksman};
	case "I_Soldier_M_F": {_loadOut = NATOMarksman};
	case "I_Sniper_F": {_loadOut = NATOMarksman};
	case "O_T_Recon_M_F": {_loadout = CSATMarksman};
	case "B_recon_medic_F": {_loadOut = NATOSpecOp select 7};
	case "B_CTRG_Soldier_Medic_tna_F": {_loadOut = NATOSpecOp select 7};
	case "I_medic_F": {_loadOut = NATOSpecOp select 7};
	case "O_T_Recon_Medic_F": {_loadOut = CSATSpecOp select 7};
	case "B_recon_LAT_F": {_loadOut = NATOSpecOp select 6};
	case "B_CTRG_Soldier_LAT_tna_F": {_loadOut = NATOSpecOp select 6};
	case "I_Soldier_LAT_F": {_loadOut = NATOSpecOp select 6};
	case "O_T_Recon_LAT_F": {_loadout = CSATSpecOp select 6};
	case "B_recon_F": {_loadOut = NATOSpecOp select 2};
	case "B_CTRG_Soldier_tna_F": {_loadOut = NATOSpecOp select 2};
	case "O_T_Recon_F": {_loadout = CSATSpecOp select 2};
	case "B_recon_JTAC_F": {_loadOut = NATOSpecOp select 1};
	case "B_CTRG_Soldier_JTAC_tna_F": {_loadOut = NATOSpecOp select 1};
	case "I_Spotter_F": {_loadOut = NATOSpecOp select 1};
	case "O_T_Recon_JTAC_F": {_loadOut = CSATSpecOp select 1};
	case "B_recon_exp_F": {_loadOut = NATOSpecOp select 5};
	case "B_CTRG_Soldier_Exp_tna_F": {_loadOut = NATOSpecOp select 5};
	case "I_Soldier_exp_F": {_loadOut = NATOSpecOp select 5};
	case "O_T_Recon_Exp_F": {_loadOut = CSATSpecOp select 5};
	case "B_Patrol_Soldier_MG_F": {_loadOut = NATOSpecOp select 3};
	case "B_CTRG_Soldier_AR_tna_F": {_loadOut = NATOSpecOp select 3};
	};
_unit setUnitLoadout _loadout;

_unit selectWeapon (primaryWeapon _unit);
